name: fluster
description: A geospatial point clustering library for Dart to help provide spacing between markers in mapping solutions.
version: 1.1.2
homepage: https://github.com/alfonsocejudo/fluster
author: Alfonso Cejudo <fonz@happeningsoft.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.7.0
  mockito: ^4.1.0
  test: ^1.6.0
